name: Add Reviewers to Open PRs

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers
        uses: actions/github-script@v7
        with:
          script: |
            const pullNumber = context.payload.pull_request.number;
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pullNumber,
              reviewers: ['udaykadaboina']
            });
            console.log(`Added reviewers to PR #${pullNumber}`);